### ISSUE TITLE
Logging in as a nonexistent user crashes the app

### ISSUE THREAD

**Issue by ghost** [BeekeeperAlex/U413-archived#62]
/var/www/shotgun_cmds/login.js:26
        if (user.password !== options.password)
                ^
TypeError: Cannot read property 'password' of null
    at Promise.<anonymous> (/var/www/shotgun_cmds/login.js:26:17)
    at Promise.<anonymous> (/var/www/node_modules/mongoose-simpledb/node_modules/mongoose/node_modules/mpromise/lib/promise.js:171:8)
    at Promise.EventEmitter.emit (events.js:95:17)
    at Promise.emit (/var/www/node_modules/mongoose-simpledb/node_modules/mongoose/node_modules/mpromise/lib/promise.js:88:38)
    at Promise.fulfill (/var/www/node_modules/mongoose-simpledb/node_modules/mongoose/node_modules/mpromise/lib/promise.js:101:20)
    at Object.cb (/var/www/node_modules/mongoose-simpledb/node_modules/mongoose/lib/query.js:1164:30)
    at Object._onImmediate (/var/www/node_modules/mongoose-simpledb/node_modules/mongoose/node_modules/mquery/lib/utils.js:126:16)
    at processImmediate [as _immediateCallback](timers.js:330:15)

**Comment by BeekeeperAlex** [comment]
[This has been fixed :)](https://github.com/chevex/U413/commit/b8a8295d4dbff1fe70c3544aee5381c34769c0e2#diff-2d51f711c193fbbd6dad911f64018fcbR26)
