### ISSUE TITLE
Certain commands entered without logging in crash the app

### ISSUE THREAD

**Issue by ghost** [BeekeeperAlex/U413-archived#65]
```
/var/www/node_modules/shotgun/utils/execute.js:45
        var cmd = shell.cmds[cmdName.toLowerCase()];
                                     ^
TypeError: Object #<Object> has no method 'toLowerCase'
    at module.exports.exports [as execute] (/var/www/node_modules/shotgun/utils/execute.js:45:38)
    at Socket.<anonymous> (/var/www/node_modules/shotgun-client/index.js:96:26)
    at Socket.EventEmitter.emit [as $emit] (events.js:106:17)
    at SocketNamespace.handlePacket (/var/www/node_modules/shotgun-client/node_modules/socket.io/lib/namespace.js:335:22)
    at Manager.onClientMessage (/var/www/node_modules/shotgun-client/node_modules/socket.io/lib/manager.js:488:38)
    at XHRPolling.Transport.onMessage (/var/www/node_modules/shotgun-client/node_modules/socket.io/lib/transport.js:387:20)
    at XHRPolling.HTTPTransport.onData (/var/www/node_modules/shotgun-client/node_modules/socket.io/lib/transports/http.js:99:10)
    at IncomingMessage.<anonymous> (/var/www/node_modules/shotgun-client/node_modules/socket.io/lib/transports/http.js:69:12)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at _stream_readable.js:920:16
```

**Comment by BeekeeperAlex** [comment]
Can you provide steps to reproduce the bug? What are the "certain commands" entered?

**Comment by ghost** [comment]
I wish I could. While spamming the link to my site on many pages, someone found a way to crash it every time. I know they weren't logged in because I kept checking 'users', and they kept doing it over and over again (this was before I had it on automatic restart so I had to restart manually every time). Have not seen this bug since, and there is a chance someone was trying to deliberately crash it but gave up when they realized it restarts anyway.

**Comment by AlexAllocated** [comment]
Well I'll fill the input field with some garbage and run some small tests but without being able to reproduce the bug we'll just have to wait for it to happen again. Perhaps all command input in the application should be dumped to a log file with timestamps for the future. I might do that if I ever have time, lol.
